
import os
import psycopg2
from psycopg2.extras import RealDictCursor

DATABASE_URL = os.getenv("DATABASE_URL")

def get_db_connection():
    return psycopg2.connect(
        DATABASE_URL,
        cursor_factory=RealDictCursor
    )

def init_db():
    connection = get_db_connection()
    cursor = connection.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT UNIQUE NOT NULL,
            email TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            created_at TEXT NOT NULL
        )
    """)

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS expenses (
            expense_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            amount DOUBLE PRECISION NOT NULL,
            category TEXT NOT NULL,
            note TEXT,
            date TEXT NOT NULL,
            payment_method TEXT NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(id)
        )
    """)

    connection.commit()
    cursor.close()
    connection.close()


def create_user(username, email, password_hash, created_at):
    connection = get_db_connection()
    cursor = connection.cursor()

    cursor.execute("""
        INSERT INTO users (username, email, password_hash, created_at)
        VALUES (%s, %s, %s, %s)
        RETURNING id
    """, (username, email, password_hash, created_at))

    user_id = cursor.fetchone()["id"]

    connection.commit()
    cursor.close()
    connection.close()

    return {
        "id": user_id,
        "username": username,
        "email": email,
        "created_at": created_at
    }


def create_expense(user_id, amount, category, note, date, payment_method):
    connection = get_db_connection()
    cursor = connection.cursor()

    cursor.execute("""
        INSERT INTO expenses
        (user_id, amount, category, note, date, payment_method)
        VALUES (%s, %s, %s, %s, %s, %s)
        RETURNING expense_id
    """, (user_id, amount, category, note, date, payment_method))

    expense_id = cursor.fetchone()["expense_id"]

    connection.commit()
    cursor.close()
    connection.close()

    return {
        "expense_id": expense_id,
        "user_id": user_id,
        "amount": amount,
        "category": category,
        "note": note,
        "date": date,
        "payment_method": payment_method
    }


def get_expenses(user_id, category=None):
    connection = get_db_connection()
    cursor = connection.cursor()

    if category:
        cursor.execute("""
            SELECT * FROM expenses
            WHERE user_id = %s AND category = %s
        """, (user_id, category))
    else:
        cursor.execute("""
            SELECT * FROM expenses
            WHERE user_id = %s
        """, (user_id,))

    expenses = cursor.fetchall()

    cursor.close()
    connection.close()

    return [dict(expense) for expense in expenses]


def get_expense_by_id(expense_id, user_id):
    connection = get_db_connection()
    cursor = connection.cursor()

    cursor.execute("""
        SELECT * FROM expenses
        WHERE expense_id = %s AND user_id = %s
    """, (expense_id, user_id))

    expense = cursor.fetchone()

    cursor.close()
    connection.close()

    if expense:
        return dict(expense)

    return None


def update_expense_in_db(
    expense_id,
    user_id,
    amount,
    category,
    note,
    date,
    payment_method
):
    connection = get_db_connection()
    cursor = connection.cursor()

    cursor.execute("""
        UPDATE expenses
        SET amount = %s,
            category = %s,
            note = %s,
            date = %s,
            payment_method = %s
        WHERE expense_id = %s AND user_id = %s
    """, (
        amount,
        category,
        note,
        date,
        payment_method,
        expense_id,
        user_id
    ))

    connection.commit()

    cursor.close()
    connection.close()


def delete_expense_in_db(expense_id, user_id):
    connection = get_db_connection()
    cursor = connection.cursor()

    cursor.execute("""
        DELETE FROM expenses
        WHERE expense_id = %s AND user_id = %s
    """, (expense_id, user_id))

    deleted = cursor.rowcount

    connection.commit()

    cursor.close()
    connection.close()

    return deleted


def get_user_by_email(email):
    connection = get_db_connection()
    cursor = connection.cursor()

    cursor.execute("""
        SELECT * FROM users
        WHERE email = %s
    """, (email,))

    user = cursor.fetchone()

    cursor.close()
    connection.close()

    if user:
        return dict(user)

    return None
